### ISSUE TITLE
Please don't use a viral license

### ISSUE THREAD

**Issue by valentinomiazzo** [endofexclusive/astub#1]
Hello, endofexclusive.
This project is really interesting.

Anyway, GPL v3 license is, IMO, a bit extreme for some code that must be linked statically to other.
It would the linked code GPL v3 too.

What about using BSD or MIT?

Thanks

**Comment by terriblefire** [comment]
I dont see why you would need to link this with anything. Its a GDB server that runs on the Amiga. GPL is appropriate for a tool like this. Please use viral licenses.

**Comment by valentinomiazzo** [comment]
Hello terriblefire, first of all my compliments for your hardware projects.

You are indeed right even if named stub this is actually a server.
